default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: project

development:
  <<: *default
  database: project_development
  password: <%= ENV.fetch("PSQL_PASSWORD") %>

test:
  <<: *default
  database: project_test
  password: <%= ENV.fetch("PSQL_PASSWORD") %>

production:
  <<: *default
  database: project_production
  username: project
  password: <%= ENV["PROJECT_DATABASE_PASSWORD"] %>
